### ISSUE TITLE
docker下载开启后无法运行

### ISSUE THREAD

**Issue by yzdily** [fengxuangit/log4j_vuln#2]
大佬，靶场搭建并开启服务后，无法运行
![image](https://user-images.githubusercontent.com/74164958/145660430-237316f5-77cc-45d8-b5e6-570033ed87cf.png)

**Comment by fengxuangit** [comment]
好好按照命令敲，肯定能运行起来 。

**Comment by fengxuangit** [comment]
`docker pull registry.cn-hangzhou.aliyuncs.com/fengxuan/log4j_vuln
docker run -it -d -p 8080:8080 --name log4j_vuln_container registry.cn-hangzhou.aliyuncs.com/fengxuan/log4j_vuln 
docker exec -it log4j_vuln_container /bin/bash
/bin/bash /home/apache-tomcat-8.5.45/bin/startup.sh `

这最后一步是需要进入到docker容器里面输入的，大哥
