### ISSUE TITLE
docker访问8080端口无应答

### ISSUE THREAD

**Issue by sovegetable** [fengxuangit/log4j_vuln#5]
docker exec进容器bash后之后然后可以访问到tomcat,之后exit退出就访问不到了一直转圈圈
![image](https://user-images.githubusercontent.com/62092842/168406405-f0112ecb-4553-4cad-872c-bf76e56e9668.png)
![image](https://user-images.githubusercontent.com/62092842/168406407-123a81ee-6f04-4c4e-9457-1e96b2734be2.png)

**Comment by fengxuangit** [comment]
是需要进入docker容器里面 然后开启服务的。如果你自己看了我的说明 肯定是能访问的。
